name: edubuild
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  google_maps_flutter: ^2.5.0
  image_picker: ^1.0.7  # ✅ Tambahan untuk ambil gambar dari galeri/kamera

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Untuk menambahkan asset (jika perlu), kamu bisa buka comment ini dan tambahkan file kamu
  # assets:
  #   - assets/images/
