// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6hHpF0Dx5O4AHGxzyr9jGw4qtlDdMkzI',
    appId: '1:1022302636357:web:2026f3b715630e1357162c',
    messagingSenderId: '1022302636357',
    projectId: 'edubuild-8f00e',
    authDomain: 'edubuild-8f00e.firebaseapp.com',
    storageBucket: 'edubuild-8f00e.firebasestorage.app',
    measurementId: 'G-WE4H0PD7XM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA32s4KGEAijLHRIFbrvbGmbZttiSWk8qw',
    appId: '1:1022302636357:android:eb9db334b073b18957162c',
    messagingSenderId: '1022302636357',
    projectId: 'edubuild-8f00e',
    storageBucket: 'edubuild-8f00e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6MUtme-UcLKd31WkiWWvAfeqs9sn92yw',
    appId: '1:1022302636357:ios:1f195c17bf9ff1df57162c',
    messagingSenderId: '1022302636357',
    projectId: 'edubuild-8f00e',
    storageBucket: 'edubuild-8f00e.firebasestorage.app',
    iosBundleId: 'com.example.edubuild',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6MUtme-UcLKd31WkiWWvAfeqs9sn92yw',
    appId: '1:1022302636357:ios:1f195c17bf9ff1df57162c',
    messagingSenderId: '1022302636357',
    projectId: 'edubuild-8f00e',
    storageBucket: 'edubuild-8f00e.firebasestorage.app',
    iosBundleId: 'com.example.edubuild',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6hHpF0Dx5O4AHGxzyr9jGw4qtlDdMkzI',
    appId: '1:1022302636357:web:2ba2ab0368073ede57162c',
    messagingSenderId: '1022302636357',
    projectId: 'edubuild-8f00e',
    authDomain: 'edubuild-8f00e.firebaseapp.com',
    storageBucket: 'edubuild-8f00e.firebasestorage.app',
    measurementId: 'G-V068CZX0D2',
  );
}
